let selected=null,preset="normal",resultUrl=null,wavUrl=null,videoUrl=null,isVideo=false;
const $=s=>document.querySelector(s), file=$("#file"),drop=$("#drop"),work=$("#work");
["dragenter","dragover"].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.add("over")}));
["dragleave","drop"].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.remove("over")}));
drop.addEventListener("drop",e=>loadFile(e.dataTransfer.files[0]));file.addEventListener("change",()=>loadFile(file.files[0]));
$("#change").onclick=()=>file.click();
document.querySelectorAll(".preset").forEach(b=>b.onclick=()=>{document.querySelectorAll(".preset").forEach(x=>x.classList.remove("active"));b.classList.add("active");preset=b.dataset.preset});
function loadFile(f){if(!f)return;isVideo=f.type.startsWith("video/")||/\.(mp4|webm|mov)$/i.test(f.name);const okAudio=f.type.startsWith("audio/")||/\.(mp3|wav|m4a|aac|ogg)$/i.test(f.name);if(!isVideo&&!okAudio){showError("Selecione um áudio ou vídeo compatível.");return}selected=f;$("#filename").textContent=f.name;const u=URL.createObjectURL(f);$("#original").classList.toggle("hidden",isVideo);$("#originalVideo").classList.toggle("hidden",!isVideo);if(isVideo)$("#originalVideo").src=u;else $("#original").src=u;drop.classList.add("hidden");work.classList.remove("hidden");["#download","#downloadWav","#downloadVideo"].forEach(s=>$(s).classList.add("hidden"));$("#resultBox").classList.add("disabled");$("#resultVideo").classList.add("hidden");$("#result").classList.remove("hidden");$("#error").classList.add("hidden");$("#process").textContent=isVideo?"✨ LIMPAR ÁUDIO DO VÍDEO":"✨ PROCESSAR ÁUDIO"}}
let ffmpegInstance=null;
async function getFFmpeg(){if(ffmpegInstance)return ffmpegInstance;if(typeof FFmpeg==="undefined")throw new Error("FFmpeg WebAssembly não carregou");const {createFFmpeg}=FFmpeg;ffmpegInstance=createFFmpeg({log:false,corePath:"https://unpkg.com/@ffmpeg/core@0.11.0/dist/ffmpeg-core.js"});setProgress(8,"Carregando motor de vídeo…");await ffmpegInstance.load();return ffmpegInstance}
async function extractAudioFromVideo(f){const ff=await getFFmpeg(),ext=(f.name.split(".").pop()||"mp4").toLowerCase(),input="entrada."+ext;ff.FS("writeFile",input,new Uint8Array(await f.arrayBuffer()));try{await ff.run("-i",input,"-vn","-acodec","pcm_s16le","-ar","48000","audio.wav");const d=ff.FS("readFile","audio.wav");return d.buffer.slice(d.byteOffset,d.byteOffset+d.byteLength)}finally{try{ff.FS("unlink",input)}catch(e){}try{ff.FS("unlink","audio.wav")}catch(e){}}}
async function muxCleanAudio(video,wavBlob){const ff=await getFFmpeg(),ext=(video.name.split(".").pop()||"mp4").toLowerCase(),input="video."+ext;ff.FS("writeFile",input,new Uint8Array(await video.arrayBuffer()));ff.FS("writeFile","clean.wav",new Uint8Array(await wavBlob.arrayBuffer()));try{await ff.run("-i",input,"-i","clean.wav","-map","0:v:0","-map","1:a:0","-c:v","copy","-c:a","aac","-b:a","192k","-shortest","saida.mp4");const d=ff.FS("readFile","saida.mp4");return new Blob([d.buffer.slice(d.byteOffset,d.byteOffset+d.byteLength)],{type:"video/mp4"})}finally{["video."+ext,"clean.wav","saida.mp4"].forEach(x=>{try{ff.FS("unlink",x)}catch(e){}})}}