let selected=null,preset="normal",resultUrl=null,wavUrl=null;
const $=s=>document.querySelector(s), file=$("#file"),drop=$("#drop"),work=$("#work");
["dragenter","dragover"].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.add("over")}));
["dragleave","drop"].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.remove("over")}));
drop.addEventListener("drop",e=>loadFile(e.dataTransfer.files[0]));file.addEventListener("change",()=>loadFile(file.files[0]));
$("#change").onclick=()=>file.click();
document.querySelectorAll(".preset").forEach(b=>b.onclick=()=>{document.querySelectorAll(".preset").forEach(x=>x.classList.remove("active"));b.classList.add("active");preset=b.dataset.preset});
function loadFile(f){if(!f)return;if(!f.type.startsWith("audio/")&&!/\.(mp3|wav|m4a|aac|ogg)$/i.test(f.name)){showError("Selecione um arquivo de áudio compatível.");return}selected=f;$("#filename").textContent=f.name;$("#original").src=URL.createObjectURL(f);drop.classList.add("hidden");work.classList.remove("hidden");$("#download").classList.add("hidden");$("#downloadWav").classList.add("hidden");$("#resultBox").classList.add("disabled");$("#error").classList.add("hidden")}
function showError(t){$("#error").textContent=t;$("#error").classList.remove("hidden")}
function setProgress(n,t){$("#progress").classList.remove("hidden");$("#bar").style.width=n+"%";$("#status").textContent=t}
$("#process").onclick=async()=>{if(!selected)return;const btn=$("#process");btn.disabled=true;$("#download").classList.add("hidden");$("#downloadWav").classList.add("hidden");$("#error").classList.add("hidden");try{
setProgress(8,"Lendo áudio…");const buf=await selected.arrayBuffer();const ctx=new (window.AudioContext||window.webkitAudioContext)();const audio=await ctx.decodeAudioData(buf.slice(0));await ctx.close();
setProgress(22,"Analisando sinal…");await tick();const out=await clean(audio,preset,$("#highpass").checked,$("#normalize").checked,p=>setProgress(22+p*.65,"Reduzindo ruído…"));
setProgress(88,"Gerando WAV…");const wav=encodeWav(out);if(wavUrl)URL.revokeObjectURL(wavUrl);wavUrl=URL.createObjectURL(wav);const aw=$("#downloadWav");aw.href=wavUrl;aw.download=selected.name.replace(/\.[^.]+$/,"")+"-limpo.wav";aw.classList.remove("hidden");
setProgress(92,"Codificando MP3…");let playable=wavUrl;try{const mp3=await encodeMp3(out,p=>setProgress(92+p*.08,"Codificando MP3…"));if(resultUrl)URL.revokeObjectURL(resultUrl);resultUrl=URL.createObjectURL(mp3);playable=resultUrl;const a=$("#download");a.href=resultUrl;a.download=selected.name.replace(/\.[^.]+$/,"")+"-limpo.mp3";a.classList.remove("hidden")}catch(mp3err){console.warn("MP3 indisponível",mp3err);showError("O áudio foi tratado, mas o encoder MP3 não carregou. O download em WAV continua disponível.")}
$("#result").src=playable;$("#resultBox").classList.remove("disabled");setProgress(100,"Pronto ✓");
}catch(e){console.error(e);showError("Não consegui processar este arquivo. Tente WAV, MP3 ou M4A em um navegador atualizado.");$("#progress").classList.add("hidden")}finally{btn.disabled=false}};
const tick=()=>new Promise(r=>setTimeout(r,20));
async function clean(audio,mode,useHP,norm,progress){const sr=audio.sampleRate,len=audio.length,ch=audio.numberOfChannels;const settings={light:[.018,.72],normal:[.028,.58],strong:[.045,.43],voice:[.034,.5]}[mode];const gate=settings[0],floor=settings[1];let channels=[];
for(let c=0;c<ch;c++){let x=new Float32Array(audio.getChannelData(c));let y=new Float32Array(len);let hp=0,prev=0,env=0;const alpha=useHP?Math.exp(-2*Math.PI*(mode==="voice"?95:70)/sr):0;const win=Math.max(1,Math.floor(sr*.012));let energy=new Float32Array(Math.ceil(len/win));for(let i=0,k=0;i<len;i+=win,k++){let s=0,n=Math.min(win,len-i);for(let j=0;j<n;j++)s+=x[i+j]*x[i+j];energy[k]=Math.sqrt(s/n)}
let sorted=Array.from(energy).sort((a,b)=>a-b),noise=sorted[Math.floor(sorted.length*.18)]||.001,thr=Math.max(gate,noise*(mode==="strong"?3.6:mode==="light"?2.0:2.8));
for(let i=0;i<len;i++){let v=x[i];if(useHP){let h=alpha*(hp+v-prev);prev=v;hp=h;v=h}let a=Math.abs(v);env=.995*env+.005*a;let target=env<thr?floor:1;let prevGain=i?Math.abs(y[i-1])/(Math.abs(v)+1e-6):target;let gain=.88*Math.min(1,prevGain)+.12*target;gain=Math.max(floor,Math.min(1,gain));y[i]=v*gain;if(mode==="voice")y[i]=Math.tanh(y[i]*1.12)/1.12}channels.push(y);progress((c+1)/ch*80);await tick()}
if(norm){let peak=0;channels.forEach(a=>{for(let v of a)peak=Math.max(peak,Math.abs(v))});if(peak>0){let g=Math.min(3,.92/peak);channels.forEach(a=>{for(let i=0;i<a.length;i++)a[i]*=g})}}progress(100);return{channels,sampleRate:sr,length:len}}
function encodeWav(o){const n=o.channels.length,sr=o.sampleRate,len=o.length,ab=new ArrayBuffer(44+len*n*2),v=new DataView(ab);const str=(p,s)=>{for(let i=0;i<s.length;i++)v.setUint8(p+i,s.charCodeAt(i))};str(0,"RIFF");v.setUint32(4,36+len*n*2,true);str(8,"WAVE");str(12,"fmt ");v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,n,true);v.setUint32(24,sr,true);v.setUint32(28,sr*n*2,true);v.setUint16(32,n*2,true);v.setUint16(34,16,true);str(36,"data");v.setUint32(40,len*n*2,true);let p=44;for(let i=0;i<len;i++)for(let c=0;c<n;c++){let s=Math.max(-1,Math.min(1,o.channels[c][i]));v.setInt16(p,s<0?s*32768:s*32767,true);p+=2}return new Blob([ab],{type:"audio/wav"})}
async function encodeMp3(o,progress){if(typeof lamejs==="undefined")throw new Error("Encoder MP3 não carregado");const sr=o.sampleRate,ch=Math.min(2,o.channels.length),kbps=192,enc=new lamejs.Mp3Encoder(ch,sr,kbps),block=1152,parts=[];const to16=(a,start,end)=>{const z=new Int16Array(end-start);for(let i=start,j=0;i<end;i++,j++){let s=Math.max(-1,Math.min(1,a[i]));z[j]=s<0?s*32768:s*32767}return z};for(let i=0;i<o.length;i+=block){let end=Math.min(i+block,o.length),buf;if(ch===1)buf=enc.encodeBuffer(to16(o.channels[0],i,end));else buf=enc.encodeBuffer(to16(o.channels[0],i,end),to16(o.channels[1],i,end));if(buf.length)parts.push(new Uint8Array(buf));if(i%(block*100)===0){progress(i/o.length*100);await tick()}}const end=enc.flush();if(end.length)parts.push(new Uint8Array(end));progress(100);return new Blob(parts,{type:"audio/mpeg"})}